# Generated by Django 4.0.3 on 2022-08-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[(1, 'Hembra'), (2, 'Macho')], max_length=20)),
                ('raza', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'animals',
            },
        ),
    ]
